### ISSUE TITLE
Cannot invoke aws lambda in ReactJS

### ISSUE THREAD

**Issue by Sheryorov** [jamesmbourne/aws4-axios#5] opened 2020-06-10 12:17 UTC
I have single page application on ReactJS. I wanted to invoke lambda that i've already created.
After creating client it throws error:
`TypeError: url_1.URL is not a constructor interceptor.js:51`

Client look like:
```
import axios from 'axios';
import { aws4Interceptor } from 'aws4-axios';

const clientWithIAM = axios.create();
clientWithIAM.interceptors.request.use(aws4Interceptor());
```

Dependencies:
```
"aws4-axios": "^1.12.0",
"axios": "^0.19.2",
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "3.4.1"
```

**Comment by jowo-io** [comment] 2020-06-11 08:22
Also having this issue!
Workaround is to downgrade axios to v0.18.1
`npm install axios@0.18.1 --save`

**Comment by vturbin** [comment] 2020-06-11 12:27
I have managed to get solve the issue by replacing line in interceptor.js file with:
 var _a = new URL(url), host = _a.host, pathname = _a.pathname, search = _a.search;

**Comment by Sheryorov** [comment] 2020-06-11 18:12
i think it should fixed on dependency level

**Comment by jamesmbourne** [comment] 2020-07-05 23:25
I've managed to reproduce this using a `create-react-app` starter with Node.js v12.18.2.

Since Node.js v10.0.0, `URL` has been available as a [global object](https://nodejs.org/api/globals.html#globals_url). This is the same behavior as in [browsers](https://developer.mozilla.org/en-US/docs/Web/API/URL).

My proposal for this would be to make use of the global URL object and avoid the complexity of dynamically importing it.

**Comment by asungomez** [comment] 2020-11-16 11:55
I'm having this issue as well, any idea on when the fix will be published? Any workaround to override behaviour without editing the interceptor.js file itself?

**Comment by cam8001** [comment] 2020-12-01 03:27
Isn't this fixed in https://github.com/jamesmbourne/aws4-axios/commit/33dc444f31e11cd03152b74b50ec4ee0a8162857? Is it cool to bump the release version to include this commit?

**Comment by jamesmbourne** [comment] 2021-01-17 15:05
Apologies for the delay - I have tested this using React and managed to send a signed request. Please feel free to open another issue if you have any trouble getting this to work.

**Closed by jamesmbourne** 2021-01-17 15:05 UTC
Labels: bug
