### ISSUE TITLE
version 3.3.0 does not preserve headers so you can't pass extra headers 

### ISSUE THREAD

**Issue by kamran-plt** [jamesmbourne/aws4-axios#1272] opened 2024-02-14 23:01 UTC
If you want to pass for example apiKey then it is not possible atm, The issue is with only Get method

**Comment by julada** [comment] 2024-02-15 08:12
> If you want to pass for example apiKey then it is not possible atm, The issue is with only Get method

happened to me for version 3.3.1. 3.3.0 works fine.

**Comment by attila** [comment] 2024-02-15 17:26
Same here as in https://github.com/jamesmbourne/aws4-axios/issues/1272#issuecomment-1945552438

In a synthetic Typescript test it works fine (source is transpiled on the fly) but not anymore once the source is built with esbuild for node 18.x.

Need to stick with 3.3.0 until fixed.

**Comment by calum-pledge-io** [comment] 2024-02-20 17:30
Seems likely that this is related to https://github.com/jamesmbourne/aws4-axios/pull/1248, which was merged in 3.3.1

**Comment by chris-gilbert-2** [comment] 2024-02-22 16:53
I *seem* to have the same problem with post requests - have checked with version 3.3.1 and 3.3.0 (and 3.2.24 just in case) running on node 18 with axios 1.6.7 - any headers I have set on axios either when creating axios or in the post call get removed. Just double checking for any silly mistakes I've made but wondering if anyone else has problems with post - original issue only mentioned get

**Comment by calum-pledge-io** [comment] 2024-02-22 16:57
I also had issues with POST requests before downgrading to 3.3.0

**Comment by chris-gilbert-2** [comment] 2024-02-22 17:20
Thank-you - I'll double check that I really did downgrade!

**Comment by jamesmbourne** [comment] 2024-03-10 14:05
Hey all, sorry to hear about this issue. Could you provide some help in reproducing this? I've added tests to ensure that headers are echoed back https://github.com/jamesmbourne/aws4-axios/pull/1299 but I'm struggling to reproduce the issue.

**Comment by calum-pledge-io** [comment] 2024-03-11 11:39
@attila's comment mentioned that they're using esbuild for bundling and running on nodejs 18, which matches my environment.
@chris-gilbert-2 I see you're running node 18; are you also bundling with esbuild, or using another bundler/not bundling and able to reproduce?

**Comment by chris-gilbert-2** [comment] 2024-03-12 09:00
Hi @calum-pledge-io 

Yes, esbuild. We are running on AWS in a Node 18 environment - here are the relevant scripts in our `package.json`

```json
  "scripts": {
    "build": "tsc && esbuild src/handlers/app.ts --minify --bundle --target=es2020 --platform=node --sourcemap --outdir=dist",
    "package": "cd dist && zip -r dist.zip . && mv dist.zip .."
  },
```

our `tsconfig.json` looks like

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "strict": true,
    "preserveConstEnums": true,
    "useDefineForClassFields": true,
    "noEmit": true,
    "sourceMap": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": false
  },
  "exclude": ["node_modules"]
}
```

**Comment by jamesmbourne** [comment] 2024-03-12 19:55
Thanks for the details @chris-gilbert-2, I managed to reproduce this issue with this information!

Seems like the change in https://github.com/jamesmbourne/aws4-axios/pull/1248 caused this. I've changed the mechanism to call `.set()` on the headersr object rather than overwriting it - this should avoid the issues reported of the object not being an instance of the AxiosHeaders class.

**Closed** 2024-03-12 20:13 UTC

**Comment by attila** [comment] 2024-03-13 07:45
It works like a charm, thank you @jamesmbourne for the fix!
